/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const Inquiry = IDL.Record({
  'service' : IDL.Text,
  'name' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const PaymentTerms = IDL.Record({
  'afterCompletion' : IDL.Nat,
  'advance' : IDL.Nat,
});
export const Pricing = IDL.Record({
  'hostingSetup' : IDL.Nat,
  'googleProfile' : IDL.Nat,
  'basicWebsite' : IDL.Nat,
  'logoDesign' : IDL.Nat,
  'googleConsole' : IDL.Nat,
  'domainSetup' : IDL.Nat,
  'standardWebsite' : IDL.Nat,
  'maintenance' : IDL.Nat,
  'landingPage' : IDL.Nat,
});
export const Service = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});
export const WorkProcessStep = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'stepNumber' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearAllInquiries' : IDL.Func([], [], []),
  'clearAllSubmissions' : IDL.Func([], [], []),
  'deleteContactSubmission' : IDL.Func(
      [IDL.Principal, IDL.Int],
      [IDL.Bool],
      [],
    ),
  'deleteServiceInquiry' : IDL.Func([IDL.Principal, IDL.Int], [IDL.Bool], []),
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(ContactSubmission)))],
      ['query'],
    ),
  'getAllServiceInquiries' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(Inquiry)))],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactSubmissions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getContactSubmissionsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getPaymentTerms' : IDL.Func([], [PaymentTerms], []),
  'getPricing' : IDL.Func([], [Pricing], []),
  'getServiceInquiries' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Inquiry)],
      ['query'],
    ),
  'getServiceInquiriesCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], []),
  'getWorkProcessSteps' : IDL.Func([], [IDL.Vec(WorkProcessStep)], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveContactSubmission' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [],
      [],
    ),
  'saveServiceInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [],
      [],
    ),
  'testMessage' : IDL.Func([], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const Inquiry = IDL.Record({
    'service' : IDL.Text,
    'name' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const PaymentTerms = IDL.Record({
    'afterCompletion' : IDL.Nat,
    'advance' : IDL.Nat,
  });
  const Pricing = IDL.Record({
    'hostingSetup' : IDL.Nat,
    'googleProfile' : IDL.Nat,
    'basicWebsite' : IDL.Nat,
    'logoDesign' : IDL.Nat,
    'googleConsole' : IDL.Nat,
    'domainSetup' : IDL.Nat,
    'standardWebsite' : IDL.Nat,
    'maintenance' : IDL.Nat,
    'landingPage' : IDL.Nat,
  });
  const Service = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  const WorkProcessStep = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'stepNumber' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearAllInquiries' : IDL.Func([], [], []),
    'clearAllSubmissions' : IDL.Func([], [], []),
    'deleteContactSubmission' : IDL.Func(
        [IDL.Principal, IDL.Int],
        [IDL.Bool],
        [],
      ),
    'deleteServiceInquiry' : IDL.Func([IDL.Principal, IDL.Int], [IDL.Bool], []),
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(ContactSubmission)))],
        ['query'],
      ),
    'getAllServiceInquiries' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(Inquiry)))],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactSubmissions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getContactSubmissionsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getPaymentTerms' : IDL.Func([], [PaymentTerms], []),
    'getPricing' : IDL.Func([], [Pricing], []),
    'getServiceInquiries' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Inquiry)],
        ['query'],
      ),
    'getServiceInquiriesCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], []),
    'getWorkProcessSteps' : IDL.Func([], [IDL.Vec(WorkProcessStep)], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveContactSubmission' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [],
        [],
      ),
    'saveServiceInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [],
        [],
      ),
    'testMessage' : IDL.Func([], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };