/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'name' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export interface Inquiry {
  'service' : string,
  'name' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export interface PaymentTerms { 'afterCompletion' : bigint, 'advance' : bigint }
export interface Pricing {
  'hostingSetup' : bigint,
  'googleProfile' : bigint,
  'basicWebsite' : bigint,
  'logoDesign' : bigint,
  'googleConsole' : bigint,
  'domainSetup' : bigint,
  'standardWebsite' : bigint,
  'maintenance' : bigint,
  'landingPage' : bigint,
}
export interface Service {
  'name' : string,
  'description' : string,
  'price' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkProcessStep {
  'title' : string,
  'description' : string,
  'stepNumber' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearAllInquiries' : ActorMethod<[], undefined>,
  'clearAllSubmissions' : ActorMethod<[], undefined>,
  'deleteContactSubmission' : ActorMethod<[Principal, bigint], boolean>,
  'deleteServiceInquiry' : ActorMethod<[Principal, bigint], boolean>,
  'getAllContactSubmissions' : ActorMethod<
    [],
    Array<[Principal, Array<ContactSubmission>]>
  >,
  'getAllServiceInquiries' : ActorMethod<
    [],
    Array<[Principal, Array<Inquiry>]>
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactSubmissions' : ActorMethod<[Principal], Array<ContactSubmission>>,
  'getContactSubmissionsCount' : ActorMethod<[], bigint>,
  'getPaymentTerms' : ActorMethod<[], PaymentTerms>,
  'getPricing' : ActorMethod<[], Pricing>,
  'getServiceInquiries' : ActorMethod<[Principal], Array<Inquiry>>,
  'getServiceInquiriesCount' : ActorMethod<[], bigint>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getWorkProcessSteps' : ActorMethod<[], Array<WorkProcessStep>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveContactSubmission' : ActorMethod<
    [string, string, string, bigint],
    undefined
  >,
  'saveServiceInquiry' : ActorMethod<
    [string, string, string, string, bigint],
    undefined
  >,
  'testMessage' : ActorMethod<[], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];